---
dist: xenial

language: python

services:
  - docker

env:
  global:
    - ANSIBLE_PIPELINING=yes
    - ANSIBLE_FORKS=16

stages:
  - "Lint"
  - "Unit test"

jobs:
  include:
    - stage: "Lint"
      install:
        - pip install 'molecule[docker]>=2.22rc1'
      script:
        - molecule lint

    - stage: "Unit test"
      install:
        - pip install 'molecule[docker]>=2.22rc1'
        - molecule create
      script:
        - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
