---
- name: SSH keypair present at client
  register: ssh_kba_keypair_result
  openssh_keypair:
    attributes: "{{ ssh_kba_keypair_attributes | default(omit) }}"
    comment: "{{ ssh_kba_keypair_comment | default(omit) }}"
    force: "{{ ssh_kba_keypair_force | default(omit) }}"
    group: "{{ ssh_kba_keypair_group | default(omit) }}"
    mode: 0600
    owner: "{{ ssh_kba_keypair_owner | default(omit) }}"
    path: "{{ ssh_kba_keypair_path }}"
    selevel: "{{ ssh_kba_keypair_selevel | default(omit) }}"
    serole: "{{ ssh_kba_keypair_serole | default(omit) }}"
    setype: "{{ ssh_kba_keypair_setype | default(omit) }}"
    seuser: "{{ ssh_kba_keypair_seuser | default(omit) }}"
    size: "{{ ssh_kba_keypair_size | default(omit) }}"
    state: present
    type: "{{ ssh_kba_keypair_type }}"

- name: SSH public key present
  when: ssh_kba_keypair_result is success
  set_fact:
    ssh_kba_keypair_pub: "{{ ssh_kba_keypair_result.public_key }}"
