---
- name: SSH home directory present at client
  delegate_to: "{{ ssh_kba_client_hostname }}"
  become: yes
  become_user: "{{ ssh_kba_client_known_hosts_owner }}"
  when: >-
      ssh_kba_client_known_hosts_path is not defined and
      ssh_kba_server_host_names_and_keys | length > 0
  file:
    path: "~/.ssh"
    state: directory
    mode: 0700

- name: SSH host keys registered at client
  delegate_to: "{{ ssh_kba_client_hostname }}"
  become: yes
  become_user: "{{ ssh_kba_client_known_hosts_owner }}"
  loop: >-
    {{ ssh_kba_server_host_names_and_keys }}
  known_hosts:
    hash_host: "{{ ssh_kba_client_known_hosts_hash_host | default(omit) }}"
    key: "{{ item.1 }}"
    name: "{{ item.0 }}"
    path: "{{ ssh_kba_client_known_hosts_path | default(omit) }}"
    state: present

- include_tasks: keypair-native.yml
  when: ssh_kba_keypair_pub is not defined and ansible_version.full is version_compare('2.8', '>=')

- include_tasks: keypair-compat.yml
  when: ssh_kba_keypair_pub is not defined and ansible_version.full is version_compare('2.8', '<')

- name: SSH home directory present at server
  delegate_to: "{{ ssh_kba_server_hostname }}"
  become: yes
  become_user: "{{ ssh_kba_server_authorized_keys_owner }}"
  when: ssh_kba_server_authorized_keys_path is not defined
  file:
    path: "~/.ssh"
    state: directory
    mode: 0700

- name: SSH public key authorized at server
  delegate_to: "{{ ssh_kba_server_hostname }}"
  become: yes
  become_user: "{{ ssh_kba_server_authorized_keys_owner }}"
  when: ssh_kba_keypair_pub is defined
  authorized_key:
    comment: "{{ ssh_kba_server_authorized_keys_comment | default(omit) }}"
    exclusive: "{{ ssh_kba_server_authorized_keys_exclusive | default(omit) }}"
    key: "{{ ssh_kba_keypair_pub }}"
    key_options: "{{ ssh_kba_server_authorized_keys_key_options | default(omit) }}"
    manage_dir: "{{ ssh_kba_server_authorized_keys_manage_dir | default(omit) }}"
    path: "{{ ssh_kba_server_authorized_keys_path | default(omit) }}"
    state: present
    user: "{{ ssh_kba_server_authorized_keys_owner }}"
