# Only use ansible enabled pre-built images with this Dockerfile, e.g.
# znerolmolecule/molecule-prebuilt

FROM {{ item.image }}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y openssh-server openssh-client && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install openssh-server openssh-clients && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y openssh-server openssh-clients && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y openssh && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache openssh-server openssh-client; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y openssh-server openssh-client && xbps-remove -O; fi

RUN ssh-keygen -A
