---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: centos-node
    image: centos
    dockerfile: Dockerfile-ssh.j2
    command: /usr/sbin/sshd -e -D
    networks:
      - name: molecule-ssh-kba
    tmpfs:
      - /run
      - /run/sshd:mode=0755

  - name: debian-node
    image: debian
    dockerfile: Dockerfile-ssh.j2
    command: /usr/sbin/sshd -e -D
    networks:
      - name: molecule-ssh-kba
    tmpfs:
      - /run
      - /run/sshd:mode=0755

  - name: fedora-node
    image: fedora
    dockerfile: Dockerfile-ssh.j2
    command: /usr/sbin/sshd -e -D
    networks:
      - name: molecule-ssh-kba
    tmpfs:
      - /run
      - /run/sshd:mode=0755

  - name: suse-node
    image: opensuse/leap
    dockerfile: Dockerfile-ssh.j2
    command: /usr/sbin/sshd -e -D
    networks:
      - name: molecule-ssh-kba
    tmpfs:
      - /run
      - /run/sshd:mode=0755

  - name: ubuntu-node
    image: ubuntu
    dockerfile: Dockerfile-ssh.j2
    command: /usr/sbin/sshd -e -D
    networks:
      - name: molecule-ssh-kba
    tmpfs:
      - /run
      - /run/sshd:mode=0755

provisioner:
  name: ansible
  inventory:
    host_vars:
      centos-node:
        ssh_kba_server_hostname: fedora-node
        ssh_kba_server_user: alpha
        ssh_kba_client_user: beta
      debian-node:
        ssh_kba_server_hostname: centos-node
        ssh_kba_server_user: gamma
        ssh_kba_client_user: delta
      ubuntu-node:
        ssh_kba_server_hostname: debian-node
        ssh_kba_server_user: epsilon
        ssh_kba_client_user: zeta
      suse-node:
        ssh_kba_server_hostname: ubuntu-node
        ssh_kba_server_user: etha
        ssh_kba_client_user: theta
      fedora-node:
        ssh_kba_server_hostname: suse-node
        ssh_kba_server_user: iota
        ssh_kba_client_user: kappa

  lint:
    name: ansible-lint

verifier:
  name: testinfra
  lint:
    name: flake8
