---
- name: Converge
  hosts: all
  tasks:

    - delegate_to: "{{ ssh_kba_server_hostname }}"
      block:
        - name: Destination user present
          user:
            name: "{{ ssh_kba_server_user }}"
            state: present

    - block:
        - name: Source user present
          user:
            name: "{{ ssh_kba_client_user }}"
            state: present

    - name: Destination values
      delegate_facts: yes
      import_role:
        name: ansible-role-ssh-kba
